# src/main.py
import argparse
import pandas as pd
from core.session_service import InMemorySessionService
from agents.uploader_agent import validate_file
from agents.eda_agent import basic_eda
from agents.viz_agent import plot_histograms, plot_correlation_heatmap
from agents.report_agent import compose_markdown_report, save_pdf_from_markdown

def run(path, outdir="output"):
    validate_file(path)
    df = pd.read_csv(path)
    ss = InMemorySessionService()
    sid = ss.create_session(user_id="local_user")
    ss.add_artifact(sid, "dataset_path", path)
    summary = basic_eda(df)
    ss.add_artifact(sid, "summary", summary)
    images = plot_histograms(df, outdir=outdir + "/images")
    heatmap = plot_correlation_heatmap(df, outdir + "/images/corr.png")
    if heatmap:
        images.append(heatmap)
    insights = "Autogenerated quick insights:\n- Rows: {}\n- Cols: {}\n".format(summary["n_rows"], summary["n_cols"])
    md = compose_markdown_report("Automated Data Analysis", summary, insights, images)
    save_pdf_from_markdown(md, outdir + "/analysis_report.pdf")
    print("Done. Report:", outdir + "/analysis_report.pdf")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--path", required=True)
    parser.add_argument("--outdir", default="output")
    args = parser.parse_args()
    run(args.path, args.outdir)
